name: CI/CD

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  Deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    needs: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Deploy To Heroku
        uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ChatHap5-rails" #Must be unique in Heroku
          heroku_email: "haikalvidya@gmail.com"